// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/entries.proto

// Protobuf Java Version: 3.25.3
package solana.storage.Entries;

public final class EntriesOuterClass {
  private EntriesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EntriesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:solana.storage.Entries.Entries)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    java.util.List<solana.storage.Entries.EntriesOuterClass.Entry> 
        getEntriesList();
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    solana.storage.Entries.EntriesOuterClass.Entry getEntries(int index);
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    int getEntriesCount();
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    java.util.List<? extends solana.storage.Entries.EntriesOuterClass.EntryOrBuilder> 
        getEntriesOrBuilderList();
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    solana.storage.Entries.EntriesOuterClass.EntryOrBuilder getEntriesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code solana.storage.Entries.Entries}
   */
  public static final class Entries extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:solana.storage.Entries.Entries)
      EntriesOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Entries.newBuilder() to construct.
    private Entries(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Entries() {
      entries_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Entries();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entries_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entries_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              solana.storage.Entries.EntriesOuterClass.Entries.class, solana.storage.Entries.EntriesOuterClass.Entries.Builder.class);
    }

    public static final int ENTRIES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<solana.storage.Entries.EntriesOuterClass.Entry> entries_;
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<solana.storage.Entries.EntriesOuterClass.Entry> getEntriesList() {
      return entries_;
    }
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends solana.storage.Entries.EntriesOuterClass.EntryOrBuilder> 
        getEntriesOrBuilderList() {
      return entries_;
    }
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    @java.lang.Override
    public int getEntriesCount() {
      return entries_.size();
    }
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    @java.lang.Override
    public solana.storage.Entries.EntriesOuterClass.Entry getEntries(int index) {
      return entries_.get(index);
    }
    /**
     * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
     */
    @java.lang.Override
    public solana.storage.Entries.EntriesOuterClass.EntryOrBuilder getEntriesOrBuilder(
        int index) {
      return entries_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < entries_.size(); i++) {
        output.writeMessage(1, entries_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < entries_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, entries_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof solana.storage.Entries.EntriesOuterClass.Entries)) {
        return super.equals(obj);
      }
      solana.storage.Entries.EntriesOuterClass.Entries other = (solana.storage.Entries.EntriesOuterClass.Entries) obj;

      if (!getEntriesList()
          .equals(other.getEntriesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getEntriesCount() > 0) {
        hash = (37 * hash) + ENTRIES_FIELD_NUMBER;
        hash = (53 * hash) + getEntriesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static solana.storage.Entries.EntriesOuterClass.Entries parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static solana.storage.Entries.EntriesOuterClass.Entries parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entries parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(solana.storage.Entries.EntriesOuterClass.Entries prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code solana.storage.Entries.Entries}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:solana.storage.Entries.Entries)
        solana.storage.Entries.EntriesOuterClass.EntriesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entries_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entries_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                solana.storage.Entries.EntriesOuterClass.Entries.class, solana.storage.Entries.EntriesOuterClass.Entries.Builder.class);
      }

      // Construct using solana.storage.Entries.EntriesOuterClass.Entries.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
        } else {
          entries_ = null;
          entriesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entries_descriptor;
      }

      @java.lang.Override
      public solana.storage.Entries.EntriesOuterClass.Entries getDefaultInstanceForType() {
        return solana.storage.Entries.EntriesOuterClass.Entries.getDefaultInstance();
      }

      @java.lang.Override
      public solana.storage.Entries.EntriesOuterClass.Entries build() {
        solana.storage.Entries.EntriesOuterClass.Entries result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public solana.storage.Entries.EntriesOuterClass.Entries buildPartial() {
        solana.storage.Entries.EntriesOuterClass.Entries result = new solana.storage.Entries.EntriesOuterClass.Entries(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(solana.storage.Entries.EntriesOuterClass.Entries result) {
        if (entriesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            entries_ = java.util.Collections.unmodifiableList(entries_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.entries_ = entries_;
        } else {
          result.entries_ = entriesBuilder_.build();
        }
      }

      private void buildPartial0(solana.storage.Entries.EntriesOuterClass.Entries result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof solana.storage.Entries.EntriesOuterClass.Entries) {
          return mergeFrom((solana.storage.Entries.EntriesOuterClass.Entries)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(solana.storage.Entries.EntriesOuterClass.Entries other) {
        if (other == solana.storage.Entries.EntriesOuterClass.Entries.getDefaultInstance()) return this;
        if (entriesBuilder_ == null) {
          if (!other.entries_.isEmpty()) {
            if (entries_.isEmpty()) {
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureEntriesIsMutable();
              entries_.addAll(other.entries_);
            }
            onChanged();
          }
        } else {
          if (!other.entries_.isEmpty()) {
            if (entriesBuilder_.isEmpty()) {
              entriesBuilder_.dispose();
              entriesBuilder_ = null;
              entries_ = other.entries_;
              bitField0_ = (bitField0_ & ~0x00000001);
              entriesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEntriesFieldBuilder() : null;
            } else {
              entriesBuilder_.addAllMessages(other.entries_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                solana.storage.Entries.EntriesOuterClass.Entry m =
                    input.readMessage(
                        solana.storage.Entries.EntriesOuterClass.Entry.parser(),
                        extensionRegistry);
                if (entriesBuilder_ == null) {
                  ensureEntriesIsMutable();
                  entries_.add(m);
                } else {
                  entriesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<solana.storage.Entries.EntriesOuterClass.Entry> entries_ =
        java.util.Collections.emptyList();
      private void ensureEntriesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          entries_ = new java.util.ArrayList<solana.storage.Entries.EntriesOuterClass.Entry>(entries_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          solana.storage.Entries.EntriesOuterClass.Entry, solana.storage.Entries.EntriesOuterClass.Entry.Builder, solana.storage.Entries.EntriesOuterClass.EntryOrBuilder> entriesBuilder_;

      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public java.util.List<solana.storage.Entries.EntriesOuterClass.Entry> getEntriesList() {
        if (entriesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(entries_);
        } else {
          return entriesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public int getEntriesCount() {
        if (entriesBuilder_ == null) {
          return entries_.size();
        } else {
          return entriesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public solana.storage.Entries.EntriesOuterClass.Entry getEntries(int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);
        } else {
          return entriesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder setEntries(
          int index, solana.storage.Entries.EntriesOuterClass.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.set(index, value);
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder setEntries(
          int index, solana.storage.Entries.EntriesOuterClass.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.set(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder addEntries(solana.storage.Entries.EntriesOuterClass.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder addEntries(
          int index, solana.storage.Entries.EntriesOuterClass.Entry value) {
        if (entriesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEntriesIsMutable();
          entries_.add(index, value);
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder addEntries(
          solana.storage.Entries.EntriesOuterClass.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder addEntries(
          int index, solana.storage.Entries.EntriesOuterClass.Entry.Builder builderForValue) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.add(index, builderForValue.build());
          onChanged();
        } else {
          entriesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder addAllEntries(
          java.lang.Iterable<? extends solana.storage.Entries.EntriesOuterClass.Entry> values) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, entries_);
          onChanged();
        } else {
          entriesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder clearEntries() {
        if (entriesBuilder_ == null) {
          entries_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          entriesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public Builder removeEntries(int index) {
        if (entriesBuilder_ == null) {
          ensureEntriesIsMutable();
          entries_.remove(index);
          onChanged();
        } else {
          entriesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public solana.storage.Entries.EntriesOuterClass.Entry.Builder getEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public solana.storage.Entries.EntriesOuterClass.EntryOrBuilder getEntriesOrBuilder(
          int index) {
        if (entriesBuilder_ == null) {
          return entries_.get(index);  } else {
          return entriesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public java.util.List<? extends solana.storage.Entries.EntriesOuterClass.EntryOrBuilder> 
           getEntriesOrBuilderList() {
        if (entriesBuilder_ != null) {
          return entriesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(entries_);
        }
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public solana.storage.Entries.EntriesOuterClass.Entry.Builder addEntriesBuilder() {
        return getEntriesFieldBuilder().addBuilder(
            solana.storage.Entries.EntriesOuterClass.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public solana.storage.Entries.EntriesOuterClass.Entry.Builder addEntriesBuilder(
          int index) {
        return getEntriesFieldBuilder().addBuilder(
            index, solana.storage.Entries.EntriesOuterClass.Entry.getDefaultInstance());
      }
      /**
       * <code>repeated .solana.storage.Entries.Entry entries = 1;</code>
       */
      public java.util.List<solana.storage.Entries.EntriesOuterClass.Entry.Builder> 
           getEntriesBuilderList() {
        return getEntriesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          solana.storage.Entries.EntriesOuterClass.Entry, solana.storage.Entries.EntriesOuterClass.Entry.Builder, solana.storage.Entries.EntriesOuterClass.EntryOrBuilder> 
          getEntriesFieldBuilder() {
        if (entriesBuilder_ == null) {
          entriesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              solana.storage.Entries.EntriesOuterClass.Entry, solana.storage.Entries.EntriesOuterClass.Entry.Builder, solana.storage.Entries.EntriesOuterClass.EntryOrBuilder>(
                  entries_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          entries_ = null;
        }
        return entriesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:solana.storage.Entries.Entries)
    }

    // @@protoc_insertion_point(class_scope:solana.storage.Entries.Entries)
    private static final solana.storage.Entries.EntriesOuterClass.Entries DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new solana.storage.Entries.EntriesOuterClass.Entries();
    }

    public static solana.storage.Entries.EntriesOuterClass.Entries getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Entries>
        PARSER = new com.google.protobuf.AbstractParser<Entries>() {
      @java.lang.Override
      public Entries parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Entries> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Entries> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public solana.storage.Entries.EntriesOuterClass.Entries getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:solana.storage.Entries.Entry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    int getIndex();

    /**
     * <code>uint64 num_hashes = 2;</code>
     * @return The numHashes.
     */
    long getNumHashes();

    /**
     * <code>bytes hash = 3;</code>
     * @return The hash.
     */
    com.google.protobuf.ByteString getHash();

    /**
     * <code>uint64 num_transactions = 4;</code>
     * @return The numTransactions.
     */
    long getNumTransactions();

    /**
     * <code>uint32 starting_transaction_index = 5;</code>
     * @return The startingTransactionIndex.
     */
    int getStartingTransactionIndex();
  }
  /**
   * Protobuf type {@code solana.storage.Entries.Entry}
   */
  public static final class Entry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:solana.storage.Entries.Entry)
      EntryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Entry.newBuilder() to construct.
    private Entry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Entry() {
      hash_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Entry();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              solana.storage.Entries.EntriesOuterClass.Entry.class, solana.storage.Entries.EntriesOuterClass.Entry.Builder.class);
    }

    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_ = 0;
    /**
     * <code>uint32 index = 1;</code>
     * @return The index.
     */
    @java.lang.Override
    public int getIndex() {
      return index_;
    }

    public static final int NUM_HASHES_FIELD_NUMBER = 2;
    private long numHashes_ = 0L;
    /**
     * <code>uint64 num_hashes = 2;</code>
     * @return The numHashes.
     */
    @java.lang.Override
    public long getNumHashes() {
      return numHashes_;
    }

    public static final int HASH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes hash = 3;</code>
     * @return The hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getHash() {
      return hash_;
    }

    public static final int NUM_TRANSACTIONS_FIELD_NUMBER = 4;
    private long numTransactions_ = 0L;
    /**
     * <code>uint64 num_transactions = 4;</code>
     * @return The numTransactions.
     */
    @java.lang.Override
    public long getNumTransactions() {
      return numTransactions_;
    }

    public static final int STARTING_TRANSACTION_INDEX_FIELD_NUMBER = 5;
    private int startingTransactionIndex_ = 0;
    /**
     * <code>uint32 starting_transaction_index = 5;</code>
     * @return The startingTransactionIndex.
     */
    @java.lang.Override
    public int getStartingTransactionIndex() {
      return startingTransactionIndex_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (index_ != 0) {
        output.writeUInt32(1, index_);
      }
      if (numHashes_ != 0L) {
        output.writeUInt64(2, numHashes_);
      }
      if (!hash_.isEmpty()) {
        output.writeBytes(3, hash_);
      }
      if (numTransactions_ != 0L) {
        output.writeUInt64(4, numTransactions_);
      }
      if (startingTransactionIndex_ != 0) {
        output.writeUInt32(5, startingTransactionIndex_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (index_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, index_);
      }
      if (numHashes_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, numHashes_);
      }
      if (!hash_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, hash_);
      }
      if (numTransactions_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, numTransactions_);
      }
      if (startingTransactionIndex_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, startingTransactionIndex_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof solana.storage.Entries.EntriesOuterClass.Entry)) {
        return super.equals(obj);
      }
      solana.storage.Entries.EntriesOuterClass.Entry other = (solana.storage.Entries.EntriesOuterClass.Entry) obj;

      if (getIndex()
          != other.getIndex()) return false;
      if (getNumHashes()
          != other.getNumHashes()) return false;
      if (!getHash()
          .equals(other.getHash())) return false;
      if (getNumTransactions()
          != other.getNumTransactions()) return false;
      if (getStartingTransactionIndex()
          != other.getStartingTransactionIndex()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getIndex();
      hash = (37 * hash) + NUM_HASHES_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumHashes());
      hash = (37 * hash) + HASH_FIELD_NUMBER;
      hash = (53 * hash) + getHash().hashCode();
      hash = (37 * hash) + NUM_TRANSACTIONS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNumTransactions());
      hash = (37 * hash) + STARTING_TRANSACTION_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + getStartingTransactionIndex();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static solana.storage.Entries.EntriesOuterClass.Entry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static solana.storage.Entries.EntriesOuterClass.Entry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static solana.storage.Entries.EntriesOuterClass.Entry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(solana.storage.Entries.EntriesOuterClass.Entry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code solana.storage.Entries.Entry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:solana.storage.Entries.Entry)
        solana.storage.Entries.EntriesOuterClass.EntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                solana.storage.Entries.EntriesOuterClass.Entry.class, solana.storage.Entries.EntriesOuterClass.Entry.Builder.class);
      }

      // Construct using solana.storage.Entries.EntriesOuterClass.Entry.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        index_ = 0;
        numHashes_ = 0L;
        hash_ = com.google.protobuf.ByteString.EMPTY;
        numTransactions_ = 0L;
        startingTransactionIndex_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return solana.storage.Entries.EntriesOuterClass.internal_static_solana_storage_Entries_Entry_descriptor;
      }

      @java.lang.Override
      public solana.storage.Entries.EntriesOuterClass.Entry getDefaultInstanceForType() {
        return solana.storage.Entries.EntriesOuterClass.Entry.getDefaultInstance();
      }

      @java.lang.Override
      public solana.storage.Entries.EntriesOuterClass.Entry build() {
        solana.storage.Entries.EntriesOuterClass.Entry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public solana.storage.Entries.EntriesOuterClass.Entry buildPartial() {
        solana.storage.Entries.EntriesOuterClass.Entry result = new solana.storage.Entries.EntriesOuterClass.Entry(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(solana.storage.Entries.EntriesOuterClass.Entry result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.index_ = index_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.numHashes_ = numHashes_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.hash_ = hash_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.numTransactions_ = numTransactions_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.startingTransactionIndex_ = startingTransactionIndex_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof solana.storage.Entries.EntriesOuterClass.Entry) {
          return mergeFrom((solana.storage.Entries.EntriesOuterClass.Entry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(solana.storage.Entries.EntriesOuterClass.Entry other) {
        if (other == solana.storage.Entries.EntriesOuterClass.Entry.getDefaultInstance()) return this;
        if (other.getIndex() != 0) {
          setIndex(other.getIndex());
        }
        if (other.getNumHashes() != 0L) {
          setNumHashes(other.getNumHashes());
        }
        if (other.getHash() != com.google.protobuf.ByteString.EMPTY) {
          setHash(other.getHash());
        }
        if (other.getNumTransactions() != 0L) {
          setNumTransactions(other.getNumTransactions());
        }
        if (other.getStartingTransactionIndex() != 0) {
          setStartingTransactionIndex(other.getStartingTransactionIndex());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                index_ = input.readUInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                numHashes_ = input.readUInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                hash_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                numTransactions_ = input.readUInt64();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                startingTransactionIndex_ = input.readUInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int index_ ;
      /**
       * <code>uint32 index = 1;</code>
       * @return The index.
       */
      @java.lang.Override
      public int getIndex() {
        return index_;
      }
      /**
       * <code>uint32 index = 1;</code>
       * @param value The index to set.
       * @return This builder for chaining.
       */
      public Builder setIndex(int value) {

        index_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 index = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0;
        onChanged();
        return this;
      }

      private long numHashes_ ;
      /**
       * <code>uint64 num_hashes = 2;</code>
       * @return The numHashes.
       */
      @java.lang.Override
      public long getNumHashes() {
        return numHashes_;
      }
      /**
       * <code>uint64 num_hashes = 2;</code>
       * @param value The numHashes to set.
       * @return This builder for chaining.
       */
      public Builder setNumHashes(long value) {

        numHashes_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 num_hashes = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumHashes() {
        bitField0_ = (bitField0_ & ~0x00000002);
        numHashes_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes hash = 3;</code>
       * @return The hash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getHash() {
        return hash_;
      }
      /**
       * <code>bytes hash = 3;</code>
       * @param value The hash to set.
       * @return This builder for chaining.
       */
      public Builder setHash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        hash_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bytes hash = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHash() {
        bitField0_ = (bitField0_ & ~0x00000004);
        hash_ = getDefaultInstance().getHash();
        onChanged();
        return this;
      }

      private long numTransactions_ ;
      /**
       * <code>uint64 num_transactions = 4;</code>
       * @return The numTransactions.
       */
      @java.lang.Override
      public long getNumTransactions() {
        return numTransactions_;
      }
      /**
       * <code>uint64 num_transactions = 4;</code>
       * @param value The numTransactions to set.
       * @return This builder for chaining.
       */
      public Builder setNumTransactions(long value) {

        numTransactions_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 num_transactions = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumTransactions() {
        bitField0_ = (bitField0_ & ~0x00000008);
        numTransactions_ = 0L;
        onChanged();
        return this;
      }

      private int startingTransactionIndex_ ;
      /**
       * <code>uint32 starting_transaction_index = 5;</code>
       * @return The startingTransactionIndex.
       */
      @java.lang.Override
      public int getStartingTransactionIndex() {
        return startingTransactionIndex_;
      }
      /**
       * <code>uint32 starting_transaction_index = 5;</code>
       * @param value The startingTransactionIndex to set.
       * @return This builder for chaining.
       */
      public Builder setStartingTransactionIndex(int value) {

        startingTransactionIndex_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 starting_transaction_index = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartingTransactionIndex() {
        bitField0_ = (bitField0_ & ~0x00000010);
        startingTransactionIndex_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:solana.storage.Entries.Entry)
    }

    // @@protoc_insertion_point(class_scope:solana.storage.Entries.Entry)
    private static final solana.storage.Entries.EntriesOuterClass.Entry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new solana.storage.Entries.EntriesOuterClass.Entry();
    }

    public static solana.storage.Entries.EntriesOuterClass.Entry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Entry>
        PARSER = new com.google.protobuf.AbstractParser<Entry>() {
      @java.lang.Override
      public Entry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Entry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Entry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public solana.storage.Entries.EntriesOuterClass.Entry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solana_storage_Entries_Entries_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solana_storage_Entries_Entries_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_solana_storage_Entries_Entry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_solana_storage_Entries_Entry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto/entries.proto\022\026solana.storage.En" +
      "tries\"9\n\007Entries\022.\n\007entries\030\001 \003(\0132\035.sola" +
      "na.storage.Entries.Entry\"v\n\005Entry\022\r\n\005ind" +
      "ex\030\001 \001(\r\022\022\n\nnum_hashes\030\002 \001(\004\022\014\n\004hash\030\003 \001" +
      "(\014\022\030\n\020num_transactions\030\004 \001(\004\022\"\n\032starting" +
      "_transaction_index\030\005 \001(\rb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_solana_storage_Entries_Entries_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_solana_storage_Entries_Entries_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solana_storage_Entries_Entries_descriptor,
        new java.lang.String[] { "Entries", });
    internal_static_solana_storage_Entries_Entry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_solana_storage_Entries_Entry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_solana_storage_Entries_Entry_descriptor,
        new java.lang.String[] { "Index", "NumHashes", "Hash", "NumTransactions", "StartingTransactionIndex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
