name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tag pushes like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '22'

      # Build Java package
      - name: Build Java package
        run: mvn package

      # Create GitHub Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # Upload Java package (JAR or other artifacts)
      - name: Upload Java Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/syncer-1.0-SNAPSHOT.jar
          asset_name: syncer-1.0-SNAPSHOT.jar
          asset_content_type: application/java-archive

